#!/usr/bin/env python3
from pathlib import Path

root = Path('.')

def replace_once(rel, old, new, label):
    p = root / rel
    text = p.read_text(encoding='utf-8')
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'{label}: expected 1 occurrence, found {count} in {rel}')
    p.write_text(text.replace(old, new, 1), encoding='utf-8')

replace_once(
    'app/src/androidTest/java/ir/sabou/inventory/data/db/ReplenishmentMigration25To26Test.kt',
    '''        open(25).use { helper ->\n            val db = helper.writableDatabase\n            db.execSQL("CREATE TABLE legacy_marker (id INTEGER PRIMARY KEY NOT NULL, value TEXT NOT NULL)")\n            db.execSQL("INSERT INTO legacy_marker(id, value) VALUES (1, 'محفوظ')")\n        }\n        open(26).use { helper ->\n            val db = helper.writableDatabase\n            db.query("SELECT value FROM legacy_marker WHERE id = 1").use { cursor ->\n                assertTrue(cursor.moveToFirst())\n                assertEquals("محفوظ", cursor.getString(0))\n            }\n            db.query("PRAGMA table_info(inventory_replenishment_policies)").use { cursor ->\n                val columns = mutableSetOf<String>()\n                while (cursor.moveToNext()) columns += cursor.getString(cursor.getColumnIndexOrThrow("name"))\n                assertTrue(columns.containsAll(setOf("itemId", "preferredSupplierId", "targetCoverDays", "leadTimeDays", "safetyStockMicros", "orderMultipleMicros", "isEnabled")))\n            }\n        }\n''',
    '''        open(25).use { helper ->\n            val db = helper.writableDatabase\n            db.execSQL("CREATE TABLE inventory_items (id INTEGER PRIMARY KEY NOT NULL)")\n            db.execSQL("CREATE TABLE suppliers (id INTEGER PRIMARY KEY NOT NULL)")\n            db.execSQL("CREATE TABLE legacy_marker (id INTEGER PRIMARY KEY NOT NULL, value TEXT NOT NULL)")\n            db.execSQL("INSERT INTO legacy_marker(id, value) VALUES (1, 'محفوظ')")\n            db.beginTransaction()\n            try {\n                MIGRATION_25_26.migrate(db)\n                db.version = 26\n                db.setTransactionSuccessful()\n            } finally { db.endTransaction() }\n            assertEquals(26, db.version)\n            db.query("SELECT value FROM legacy_marker WHERE id = 1").use { cursor ->\n                assertTrue(cursor.moveToFirst())\n                assertEquals("محفوظ", cursor.getString(0))\n            }\n            db.query("PRAGMA table_info(inventory_replenishment_policies)").use { cursor ->\n                val columns = mutableSetOf<String>()\n                while (cursor.moveToNext()) columns += cursor.getString(cursor.getColumnIndexOrThrow("name"))\n                assertTrue(columns.containsAll(setOf("itemId", "preferredSupplierId", "targetCoverDays", "leadTimeDays", "safetyStockMicros", "orderMultipleMicros", "isEnabled")))\n            }\n            db.query("PRAGMA foreign_key_check").use { cursor -> assertEquals(0, cursor.count) }\n        }\n''',
    'replenishment valid atomic fixture',
)

replace_once(
    'app/src/androidTest/java/ir/sabou/inventory/data/db/SupplierCatalogMigration26To27Test.kt',
    '''        open(26).use { it.writableDatabase.execSQL("CREATE TABLE marker (id INTEGER PRIMARY KEY NOT NULL, value TEXT NOT NULL)"); it.writableDatabase.execSQL("INSERT INTO marker VALUES (1, 'محفوظ')") }\n        open(27).use { helper ->\n            helper.writableDatabase.query("SELECT value FROM marker").use { cursor -> assertTrue(cursor.moveToFirst()); assertEquals("محفوظ", cursor.getString(0)) }\n            helper.writableDatabase.query("PRAGMA table_info(supplier_item_offers)").use { cursor ->\n                val columns = mutableSetOf<String>(); while (cursor.moveToNext()) columns += cursor.getString(cursor.getColumnIndexOrThrow("name"))\n                assertTrue(columns.containsAll(setOf("supplierId", "itemId", "unitCostRial", "minimumOrderMicros", "orderMultipleMicros", "leadTimeDays", "validUntilEpochDay")))\n            }\n        }\n''',
    '''        open(26).use { helper ->\n            val db = helper.writableDatabase\n            db.execSQL("CREATE TABLE suppliers (id INTEGER PRIMARY KEY NOT NULL)")\n            db.execSQL("CREATE TABLE inventory_items (id INTEGER PRIMARY KEY NOT NULL)")\n            db.execSQL("CREATE TABLE marker (id INTEGER PRIMARY KEY NOT NULL, value TEXT NOT NULL)")\n            db.execSQL("INSERT INTO marker VALUES (1, 'محفوظ')")\n            db.beginTransaction()\n            try {\n                MIGRATION_26_27.migrate(db)\n                db.version = 27\n                db.setTransactionSuccessful()\n            } finally { db.endTransaction() }\n            assertEquals(27, db.version)\n            db.query("SELECT value FROM marker").use { cursor -> assertTrue(cursor.moveToFirst()); assertEquals("محفوظ", cursor.getString(0)) }\n            db.query("PRAGMA table_info(supplier_item_offers)").use { cursor ->\n                val columns = mutableSetOf<String>(); while (cursor.moveToNext()) columns += cursor.getString(cursor.getColumnIndexOrThrow("name"))\n                assertTrue(columns.containsAll(setOf("supplierId", "itemId", "unitCostRial", "minimumOrderMicros", "orderMultipleMicros", "leadTimeDays", "validUntilEpochDay")))\n            }\n            db.query("PRAGMA foreign_key_check").use { cursor -> assertEquals(0, cursor.count) }\n        }\n''',
    'supplier catalog valid atomic fixture',
)

replace_once(
    'app/src/androidTest/java/ir/sabou/inventory/data/db/SupplierPerformanceMigration24To25Test.kt',
    '''        open(24).use { helper ->\n            val db = helper.writableDatabase\n            db.execSQL("CREATE TABLE purchase_order_lines (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, purchaseOrderId INTEGER NOT NULL, itemId INTEGER NOT NULL, itemNameSnapshot TEXT NOT NULL, orderedQtyMicros INTEGER NOT NULL, unitCostRial INTEGER NOT NULL, receivedQtyMicros INTEGER NOT NULL, rejectedQtyMicros INTEGER NOT NULL)")\n            db.execSQL("INSERT INTO purchase_order_lines(purchaseOrderId,itemId,itemNameSnapshot,orderedQtyMicros,unitCostRial,receivedQtyMicros,rejectedQtyMicros) VALUES (1,2,'قهوه',1000000,500000,1000000,0)")\n        }\n        open(25).use { helper ->\n            val db = helper.writableDatabase\n            db.query("SELECT itemNameSnapshot,returnedQtyMicros FROM purchase_order_lines").use { cursor ->\n                assertTrue(cursor.moveToFirst())\n                assertEquals("قهوه", cursor.getString(0))\n                assertEquals(0L, cursor.getLong(1))\n            }\n            listOf("purchase_returns", "purchase_return_lines", "supplier_credits").forEach { table ->\n                db.query("SELECT COUNT(*) FROM $table").use { cursor -> assertTrue(cursor.moveToFirst()) }\n            }\n        }\n''',
    '''        open(24).use { helper ->\n            val db = helper.writableDatabase\n            db.execSQL("CREATE TABLE purchase_orders (id INTEGER PRIMARY KEY NOT NULL)")\n            db.execSQL("CREATE TABLE purchases (id INTEGER PRIMARY KEY NOT NULL)")\n            db.execSQL("CREATE TABLE suppliers (id INTEGER PRIMARY KEY NOT NULL)")\n            db.execSQL("CREATE TABLE inventory_items (id INTEGER PRIMARY KEY NOT NULL)")\n            db.execSQL("INSERT INTO purchase_orders(id) VALUES(1)")\n            db.execSQL("INSERT INTO suppliers(id) VALUES(1)")\n            db.execSQL("INSERT INTO inventory_items(id) VALUES(2)")\n            db.execSQL("CREATE TABLE purchase_order_lines (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, purchaseOrderId INTEGER NOT NULL, itemId INTEGER NOT NULL, itemNameSnapshot TEXT NOT NULL, orderedQtyMicros INTEGER NOT NULL, unitCostRial INTEGER NOT NULL, receivedQtyMicros INTEGER NOT NULL, rejectedQtyMicros INTEGER NOT NULL)")\n            db.execSQL("INSERT INTO purchase_order_lines(purchaseOrderId,itemId,itemNameSnapshot,orderedQtyMicros,unitCostRial,receivedQtyMicros,rejectedQtyMicros) VALUES (1,2,'قهوه',1000000,500000,1000000,0)")\n            db.beginTransaction()\n            try {\n                MIGRATION_24_25.migrate(db)\n                db.version = 25\n                db.setTransactionSuccessful()\n            } finally { db.endTransaction() }\n            assertEquals(25, db.version)\n            db.query("SELECT itemNameSnapshot,returnedQtyMicros FROM purchase_order_lines").use { cursor ->\n                assertTrue(cursor.moveToFirst())\n                assertEquals("قهوه", cursor.getString(0))\n                assertEquals(0L, cursor.getLong(1))\n            }\n            listOf("purchase_returns", "purchase_return_lines", "supplier_credits").forEach { table ->\n                db.query("SELECT COUNT(*) FROM $table").use { cursor -> assertTrue(cursor.moveToFirst()) }\n            }\n            db.query("PRAGMA foreign_key_check").use { cursor -> assertEquals(0, cursor.count) }\n        }\n''',
    'supplier performance valid atomic fixture',
)

for rel in [
    'app/src/androidTest/java/ir/sabou/inventory/data/db/ReplenishmentMigration25To26Test.kt',
    'app/src/androidTest/java/ir/sabou/inventory/data/db/SupplierCatalogMigration26To27Test.kt',
    'app/src/androidTest/java/ir/sabou/inventory/data/db/SupplierPerformanceMigration24To25Test.kt',
]:
    t = (root / rel).read_text(encoding='utf-8')
    for token in ['beginTransaction()', 'setTransactionSuccessful()', 'PRAGMA foreign_key_check']:
        if token not in t: raise SystemExit(f'fix11 guard missing {token} in {rel}')

print('DASHBOARD_UX2_FIX11_API23_VALID_MIGRATION_FIXTURES=PASS replenishment=1 supplier_catalog=1 supplier_performance=1')
