package ir.restaurant.management.domain.security

enum class Permission(val title: String) {
    BRANCH_MANAGE("مدیریت شعب"),
    PURCHASES("خرید"),
    SUPPLIERS("تأمین‌کنندگان"),
    INVENTORY("انبار"),
    RECIPES("رسپی"),
    SALES("فروش"),
    CUSTOMERS("مشتریان"),
    ACCOUNTING("حسابداری"),
    REPORTS("گزارش‌ها"),
    AUDIT("حسابرسی"),
    AUDIT_VIEW("مشاهده رویدادهای سیستم"),
    AUDIT_EXPORT("خروجی رویدادهای سیستم"),
    AUDIT_SENSITIVE_VIEW("مشاهده جزئیات حساس حسابرسی"),
    PERSONNEL("پرسنل"),
    PERSONNEL_VIEW("مشاهده پرسنل"),
    PERSONNEL_EDIT("ویرایش پرسنل"),
    PERSONNEL_CONFIDENTIAL_VIEW("مشاهده اطلاعات محرمانه پرسنل"),
    CONTRACT_CREATE("ثبت قرارداد"),
    SHIFT_MANAGE("مدیریت شیفت و برنامه کاری"),
    ATTENDANCE_EDIT("ثبت و اصلاح درخواست حضور"),
    ATTENDANCE_CORRECTION_APPROVE("تأیید اصلاح حضور"),
    OVERTIME_APPROVE("تأیید اضافه‌کار"),
    LEAVE_GRANT("اعطای سهمیه مرخصی"),
    ADVANCE_CREATE("ثبت مساعده"),
    ADVANCE_SETTLE("تسویه مساعده"),
    LOAN_CREATE("ثبت وام"),
    LOAN_APPROVE("تأیید وام"),
    HR_DOCUMENT_VIEW("مشاهده اسناد منابع انسانی"),
    HR_DOCUMENT_MANAGE("مدیریت اسناد منابع انسانی"),
    ASSETS("دارایی ثابت"),
    BACKUP("پشتیبان و خروجی"),
    MANAGE_USERS("مدیریت کاربران"),
    INVENTORY_ADJUST("تأیید اصلاح موجودی"),
    INVENTORY_PERIOD_CLOSE("بستن دوره انبار"),
    INVENTORY_VIEW("مشاهده انبار"),
    INVENTORY_ITEM_MANAGE("مدیریت کالای انبار"),
    INVENTORY_LOCATION_MANAGE("مدیریت محل‌های انبار"),
    INVENTORY_LOT_MANAGE("مدیریت لات و انقضا"),
    INVENTORY_COUNT_CREATE("ایجاد انبارگردانی"),
    INVENTORY_COUNT_PERFORM("انجام شمارش"),
    INVENTORY_COUNT_APPROVE("تأیید انبارگردانی"),
    INVENTORY_COUNT_POST("ثبت نهایی انبارگردانی"),
    INVENTORY_WASTE_CREATE("ثبت ضایعات"),
    INVENTORY_WASTE_APPROVE("تأیید ضایعات"),
    INVENTORY_TRANSFER_CREATE("ایجاد انتقال انبار"),
    INVENTORY_TRANSFER_ISSUE("خروج انتقال انبار"),
    INVENTORY_TRANSFER_RECEIVE("دریافت انتقال انبار"),
    PURCHASE_APPROVE("تأیید درخواست خرید"),
    PURCHASE_VARIANCE_APPROVE("تأیید مغایرت قیمت خرید"),
    PAYMENT_APPROVE("تأیید پرداخت"),
    PAYROLL_APPROVE("تأیید نهایی حقوق"),
    EMPLOYEE_SENSITIVE_EDIT("ویرایش اطلاعات حساس پرسنل"),
    CONTRACT_APPROVE("تأیید قرارداد"),
    ATTENDANCE_CORRECT("اصلاح حضور و غیاب"),
    LEAVE_APPROVE("تأیید مرخصی"),
    PAYROLL_VIEW_OWN("مشاهده فیش شخصی"),
    PAYROLL_VIEW_ALL("مشاهده حقوق پرسنل"),
    PAYROLL_CREATE("ایجاد دوره و دسته حقوق"),
    PAYROLL_CALCULATE("محاسبه حقوق"),
    PAYROLL_REVIEW("بازبینی حقوق"),
    PAYROLL_REVERSE("برگشت حقوق"),
    PAYROLL_PAY("پرداخت حقوق"),
    JOURNAL_REVERSE("برگشت سند حسابداری"),
    ACCOUNTING_PERIOD_CLOSE("بستن دوره مالی"),
    SALES_DAY_CLOSE("بستن روز فروش"),
    RESTORE("بازیابی اطلاعات"),
    EXPORT("خروجی اطلاعات"),
    TREASURY("خزانه‌داری"),
    RECIPE_ACTIVATE("فعال‌سازی نسخه رسپی"),
    ASSET_LIFECYCLE("عملیات چرخه عمر دارایی"),
    CUSTOMER_MERGE("ادغام مشتری"),
    CREDIT_OVERRIDE("عبور کنترل‌شده از سقف اعتبار"),
    DAILY_SALES_VIEW("مشاهده فروش روزانه"),
    DAILY_SALES_CREATE("ایجاد فروش روزانه"),
    DAILY_SALES_EDIT("ویرایش فروش روزانه"),
    DAILY_SALES_CONFIRM("تأیید فروش روزانه"),
    DAILY_SALES_POST("ثبت نهایی فروش روزانه"),
    DAILY_SALES_VOID("ابطال فروش روزانه"),
    RECEIVABLE_VIEW("مشاهده مطالبات"),
    RECEIVABLE_CREATE("ایجاد مطالبات"),
    RECEIVABLE_COLLECT("وصول مطالبات"),
    RECEIVABLE_ADJUST("اصلاح مطالبات"),
    CORPORATE_SALES_VIEW("مشاهده فروش شرکتی"),
    CORPORATE_SALES_MANAGE("مدیریت فروش شرکتی"),
    CONTROL_VIEW("مشاهده کنترل مدیریتی"),
    CONTROL_ASSIGN("ارجاع مسئله مدیریتی"),
    CONTROL_RESOLVE("حل مسئله مدیریتی"),
    TASK_VIEW("مشاهده وظایف مدیریتی"),
    TASK_CREATE("ایجاد وظیفه مدیریتی"),
    TASK_ASSIGN("ارجاع وظیفه مدیریتی"),
    TASK_COMPLETE("تکمیل وظیفه مدیریتی"),
    TASK_APPROVE("تأیید وظیفه مدیریتی"),
    CHECKLIST_VIEW("مشاهده چک‌لیست"),
    CHECKLIST_MANAGE("مدیریت چک‌لیست"),
    CHECKLIST_PERFORM("اجرای چک‌لیست"),
    CHECKLIST_APPROVE("تأیید چک‌لیست"),
    DAILY_BRIEF_VIEW("مشاهده خلاصه مدیریتی روزانه"),
}

enum class UserRole(
    val title: String,
    private val grantedPermissions: Set<Permission>,
) {
    OWNER("مالک", Permission.entries.toSet()),
    MANAGER(
        "مدیر",
        setOf(
            Permission.BRANCH_MANAGE,
            Permission.PURCHASES,
            Permission.SUPPLIERS,
            Permission.INVENTORY,
            Permission.RECIPES,
            Permission.SALES,
            Permission.DAILY_SALES_VIEW, Permission.DAILY_SALES_CREATE, Permission.DAILY_SALES_EDIT, Permission.DAILY_SALES_CONFIRM, Permission.DAILY_SALES_POST, Permission.DAILY_SALES_VOID,
            Permission.RECEIVABLE_VIEW, Permission.RECEIVABLE_CREATE, Permission.RECEIVABLE_COLLECT, Permission.RECEIVABLE_ADJUST,
            Permission.CORPORATE_SALES_VIEW, Permission.CORPORATE_SALES_MANAGE,
            Permission.CONTROL_VIEW, Permission.CONTROL_ASSIGN, Permission.CONTROL_RESOLVE,
            Permission.TASK_VIEW, Permission.TASK_CREATE, Permission.TASK_ASSIGN, Permission.TASK_COMPLETE, Permission.TASK_APPROVE,
            Permission.CHECKLIST_VIEW, Permission.CHECKLIST_MANAGE, Permission.CHECKLIST_PERFORM, Permission.CHECKLIST_APPROVE,
            Permission.DAILY_BRIEF_VIEW,
            Permission.CUSTOMERS,
            Permission.ACCOUNTING,
            Permission.REPORTS,
            Permission.AUDIT,
            Permission.AUDIT_VIEW,
            Permission.AUDIT_EXPORT,
            Permission.PERSONNEL,
            Permission.PERSONNEL_VIEW,
            Permission.PERSONNEL_EDIT,
            Permission.PERSONNEL_CONFIDENTIAL_VIEW,
            Permission.CONTRACT_CREATE,
            Permission.SHIFT_MANAGE,
            Permission.ATTENDANCE_EDIT,
            Permission.ATTENDANCE_CORRECTION_APPROVE,
            Permission.OVERTIME_APPROVE,
            Permission.LEAVE_GRANT,
            Permission.ADVANCE_CREATE,
            Permission.ADVANCE_SETTLE,
            Permission.LOAN_CREATE,
            Permission.LOAN_APPROVE,
            Permission.HR_DOCUMENT_VIEW,
            Permission.HR_DOCUMENT_MANAGE,
            Permission.ASSETS,
            Permission.INVENTORY_ADJUST,
            Permission.INVENTORY_PERIOD_CLOSE,
            Permission.INVENTORY_VIEW,
            Permission.INVENTORY_ITEM_MANAGE,
            Permission.INVENTORY_LOCATION_MANAGE,
            Permission.INVENTORY_LOT_MANAGE,
            Permission.INVENTORY_COUNT_CREATE,
            Permission.INVENTORY_COUNT_PERFORM,
            Permission.INVENTORY_COUNT_APPROVE,
            Permission.INVENTORY_COUNT_POST,
            Permission.INVENTORY_WASTE_CREATE,
            Permission.INVENTORY_WASTE_APPROVE,
            Permission.INVENTORY_TRANSFER_CREATE,
            Permission.INVENTORY_TRANSFER_ISSUE,
            Permission.INVENTORY_TRANSFER_RECEIVE,
            Permission.PURCHASE_APPROVE,
            Permission.PURCHASE_VARIANCE_APPROVE,
            Permission.PAYMENT_APPROVE,
            Permission.EMPLOYEE_SENSITIVE_EDIT,
            Permission.CONTRACT_APPROVE,
            Permission.ATTENDANCE_CORRECT,
            Permission.LEAVE_APPROVE,
            Permission.PAYROLL_VIEW_ALL,
            Permission.PAYROLL_CREATE,
            Permission.PAYROLL_CALCULATE,
            Permission.PAYROLL_REVIEW,
            Permission.JOURNAL_REVERSE,
            Permission.ACCOUNTING_PERIOD_CLOSE,
            Permission.SALES_DAY_CLOSE,
            Permission.EXPORT,
            Permission.TREASURY,
            Permission.RECIPE_ACTIVATE,
            Permission.ASSET_LIFECYCLE,
            Permission.CUSTOMER_MERGE,
            Permission.CREDIT_OVERRIDE,
        ),
    ),
    CASHIER("صندوقدار", setOf(Permission.SALES, Permission.DAILY_SALES_VIEW, Permission.CUSTOMERS, Permission.REPORTS)),
    INVENTORY(
        "انبار",
        setOf(
            Permission.INVENTORY,
            Permission.INVENTORY_VIEW,
            Permission.INVENTORY_ITEM_MANAGE,
            Permission.INVENTORY_LOCATION_MANAGE,
            Permission.INVENTORY_LOT_MANAGE,
            Permission.INVENTORY_COUNT_CREATE,
            Permission.INVENTORY_COUNT_PERFORM,
            Permission.INVENTORY_WASTE_CREATE,
            Permission.INVENTORY_TRANSFER_CREATE,
            Permission.INVENTORY_TRANSFER_ISSUE,
            Permission.INVENTORY_TRANSFER_RECEIVE,
        ),
    ),
    STOREKEEPER(
        "انباردار",
        setOf(
            Permission.PURCHASES,
            Permission.SUPPLIERS,
            Permission.INVENTORY,
            Permission.RECIPES,
            Permission.INVENTORY_ADJUST,
            Permission.INVENTORY_VIEW,
            Permission.INVENTORY_ITEM_MANAGE,
            Permission.INVENTORY_LOCATION_MANAGE,
            Permission.INVENTORY_LOT_MANAGE,
            Permission.INVENTORY_COUNT_CREATE,
            Permission.INVENTORY_COUNT_PERFORM,
            Permission.INVENTORY_WASTE_CREATE,
            Permission.INVENTORY_TRANSFER_CREATE,
            Permission.INVENTORY_TRANSFER_ISSUE,
            Permission.INVENTORY_TRANSFER_RECEIVE,
        ),
    ),
    ACCOUNTANT(
        "حسابدار",
        setOf(
            Permission.PURCHASES,
            Permission.SALES,
            Permission.CUSTOMERS,
            Permission.ACCOUNTING,
            Permission.REPORTS,
            Permission.AUDIT,
            Permission.AUDIT_VIEW,
            Permission.AUDIT_EXPORT,
            Permission.PERSONNEL,
            Permission.PERSONNEL_VIEW,
            Permission.ADVANCE_CREATE,
            Permission.ADVANCE_SETTLE,
            Permission.HR_DOCUMENT_VIEW,
            Permission.ASSETS,
            Permission.PAYMENT_APPROVE,
            Permission.PAYROLL_VIEW_ALL,
            Permission.PAYROLL_CREATE,
            Permission.PAYROLL_CALCULATE,
            Permission.PAYROLL_REVIEW,
            Permission.PAYROLL_PAY,
            Permission.JOURNAL_REVERSE,
            Permission.ACCOUNTING_PERIOD_CLOSE,
            Permission.EXPORT,
            Permission.TREASURY,
            Permission.CUSTOMER_MERGE,
            Permission.CREDIT_OVERRIDE,
            Permission.ASSET_LIFECYCLE,
        ),
    ),
    RESTRICTED("نقش محدود", emptySet());

    fun allows(permission: Permission): Boolean = permission in grantedPermissions

    companion object {
        fun fromStoredValue(value: String): UserRole =
            entries.firstOrNull { it.name == value.trim().uppercase() } ?: RESTRICTED
    }
}
